### ISSUE TITLE
No associated gemfile

### ISSUE THREAD

**Issue by sarangan12** [Azure-Samples/storage-blob-ruby-getting-started#1]
This project does not have an associated gemfile and/or clear instructions on running the sample.

**Comment by johanburati** [comment]
The only gem you need is the azure-storage gem, you can install it with the following command:
`gem install azure-storage -v 0.10.0.preview --pre`

As for the instructions, you can refer to the "Running this sample" section on the wiki:
https://github.com/Azure-Samples/storage-blob-ruby-getting-started/wiki

**Comment by robinsh** [comment]
@sarangan12 @johanburati Let me track down someone on the Storage team who does Ruby. I'll check and get back to you.

**Comment by seguler** [comment]
Ok - I will address this in README.md. Thanks for reporting this!
